CREATE TABLE IF NOT EXISTS lists (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
    name TEXT NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    user_name TEXT NOT NULL,
    category TEXT,
    list_id uuid REFERENCES lists(id) ON DELETE CASCADE
);

INSERT INTO lists (name)
VALUES ('shopping_list'), ('daily_task')
ON CONFLICT (name) DO NOTHING;
